### PR TITLE
Add PhysX Contact generation that responds to getContactPoints

### PR DESCRIPTION
**Pull request by frk2**
- Adds contact generation so we get SOMETHING.

TODO: 
- add body 'ids' somehow and bubble them back up

### CODE REVIEW

**Comment by erwincoumans** [comment]
Thanks for the PR. Body ids could be added to the [MyPhysXUserData](https://github.com/erwincoumans/bullet3/blob/physx/examples/SharedMemory/physx/URDF2PhysX.cpp#L794). I probably re-implement your PR, since I like to stay away from too much STL and using all those strings etc. Your PR still helps speeding it up, I can copy/paste some of it, so thank you!

**Comment by frk2** [comment]
Cool no prob. Im a big STL fan :) I had to quickly do this to ensure collisions were actually being reported semi-correctly so haven't had the time to clean it up but hopefully it lets you copy/paste some stuff :+1:

**Comment by erwincoumans** [comment]
Implemented it here, although still disabled.
https://github.com/erwincoumans/bullet3/commit/3bf27cf8f25236ea115eddea440d143d6c375b34
Does PhysX provide a contact callback for all contacts, every frame, so we can update contact forces after each simulation step, for all contacts?
The onContact seems only called when a contact is created, not when updated/removed?

**Comment by erwincoumans** [comment]
Latest version of this branch has the --enableContactCallback=1 option, so let's close this issue.

**Pull request closed without merging**
